spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wiyata
    username: postgres
    password: NOVIANTO

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG